'use strict';
const a = 1;
const b = 8;
const c = 9;  
let discriminant=b * b - 4 * a * c;
let solutionA = 0;
let solutionB = 0;
solutionA+=(-b + Math.sqrt(discriminant))/(2*a);
solutionB+=(-b - Math.sqrt(discriminant))/(2*a);
console.log(solutionA, solutionB);
